apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - action-check.yaml
  - build-check.yaml
  - config-check.yaml
  - custom-pipeline-check.yaml
  - deploy-comment-check.yaml
  - deployment-check.yaml
  - issue-check.yaml
  - overlay-deploy.yaml
  - overlays-pipeline-check.yaml
  - overlays-set.yaml
  - retest-comment-check.yaml
  - sibling-check.yaml
  - upload-pulp-pypi-check.yaml
  - upload-pypi-check.yaml
