apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - issue-pipeline.yaml
  - gather-deployment-metrics-pipeline.yaml
  - overlays-release-pipeline.yaml
  - pull-request-pipeline.yaml
  - tag-release-pipeline.yaml
  - z-stream-release-pipeline.yaml
  - z-stream-update-rhods.yaml
