# This templates are to serve the tekton trigger v0.8.1 and above
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git-issue-template.yaml
  - git-model-template.yaml
  - git-pr-template.yaml
  - git-tag-template.yaml
  - z-stream-release-template.yaml
